---
  name: Ensure required packages for Docker are installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes
  environment:
    http_proxy: "{{ proxy_url }}"
    https_proxy: "{{ proxy_url }}"

- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /usr/share/keyrings/docker-archive-keyring.gpg
    mode: '0644'
  environment:
    http_proxy: "{{ proxy_url }}"
    https_proxy: "{{ proxy_url }}"

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker
  environment:
    http_proxy: "{{ proxy_url }}"
    https_proxy: "{{ proxy_url }}"

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
  environment:
    http_proxy: "{{ proxy_url }}"
    https_proxy: "{{ proxy_url }}"

- name: Ensure Docker service is started and enabled
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Install Docker Compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  environment:
    http_proxy: "{{ proxy_url }}"
    https_proxy: "{{ proxy_url }}"
- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes


